"""phase 5 assigned workflow runtime"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "1223fa111b4c"
down_revision = "e049d194ba38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_number", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("current_node", sa.String(length=60), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('active','returned','approved','closed','rejected') "
            "AND revision>0 AND workflow_number>0",
            name=op.f("ck_workflow_instances_workflow_instance_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "submission_id", "owner_id"],
            [
                "submissions.organization_id",
                "submissions.workspace_id",
                "submissions.id",
                "submissions.owner_id",
            ],
            name=op.f("fk_workflow_instances_organization_id_submissions"),
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "workflow_id",
                "workflow_version_id",
                "workflow_number",
            ],
            [
                "workflow_versions.organization_id",
                "workflow_versions.workspace_id",
                "workflow_versions.workflow_id",
                "workflow_versions.id",
                "workflow_versions.number",
            ],
            name=op.f("fk_workflow_instances_organization_id_workflow_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_instances")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_workflow_instance_scope"
        ),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "submission_id", name="uq_workflow_submission"
        ),
    )
    op.create_index(
        "ix_workflow_instance_scope_cursor",
        "workflow_instances",
        ["organization_id", "workspace_id", "workflow_id", "id"],
        unique=False,
    )
    op.create_table(
        "workflow_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("node_key", sa.String(length=60), nullable=False),
        sa.Column("visit", sa.Integer(), nullable=False),
        sa.Column("recipient_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "visit > 0", name=op.f("ck_workflow_notifications_workflow_notification_visit")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "instance_id"],
            [
                "workflow_instances.organization_id",
                "workflow_instances.workspace_id",
                "workflow_instances.id",
            ],
            name=op.f("fk_workflow_notifications_organization_id_workflow_instances"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_notifications")),
        sa.UniqueConstraint(
            "organization_id",
            "instance_id",
            "node_key",
            "visit",
            name="uq_workflow_notification_visit",
        ),
    )
    op.create_index(
        "ix_workflow_notification_cursor",
        "workflow_notifications",
        ["organization_id", "id"],
        unique=False,
    )
    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("node_key", sa.String(length=60), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "number > 0 AND state IN ('open','completed','returned','rejected')",
            name=op.f("ck_workflow_steps_workflow_step_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "instance_id"],
            [
                "workflow_instances.organization_id",
                "workflow_instances.workspace_id",
                "workflow_instances.id",
            ],
            name=op.f("fk_workflow_steps_organization_id_workflow_instances"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_steps")),
        sa.UniqueConstraint(
            "organization_id", "instance_id", "number", name="uq_workflow_step_visit"
        ),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "instance_id", "id", name="uq_workflow_step_scope"
        ),
    )
    op.create_index(
        "ix_workflow_step_instance",
        "workflow_steps",
        ["organization_id", "workspace_id", "instance_id", "number"],
        unique=False,
    )
    op.create_table(
        "workflow_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('review','approve','return','reject') AND length(reason) BETWEEN 1 AND 2000",
            name=op.f("ck_workflow_actions_workflow_action_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_workflow_actions_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "instance_id", "step_id"],
            [
                "workflow_steps.organization_id",
                "workflow_steps.workspace_id",
                "workflow_steps.instance_id",
                "workflow_steps.id",
            ],
            name=op.f("fk_workflow_actions_organization_id_workflow_steps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_actions")),
        sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_workflow_action_key"),
        sa.UniqueConstraint(
            "organization_id", "step_id", "actor_id", name="uq_workflow_action_actor"
        ),
    )
    op.create_index(
        "ix_workflow_action_history",
        "workflow_actions",
        ["organization_id", "workspace_id", "instance_id", "id"],
        unique=False,
    )
    op.create_table(
        "workflow_recipients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_workflow_recipients_workflow_recipient_position")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_workflow_recipients_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "instance_id", "step_id"],
            [
                "workflow_steps.organization_id",
                "workflow_steps.workspace_id",
                "workflow_steps.instance_id",
                "workflow_steps.id",
            ],
            name=op.f("fk_workflow_recipients_organization_id_workflow_steps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_recipients")),
        sa.UniqueConstraint(
            "organization_id", "step_id", "position", name="uq_workflow_recipient_order"
        ),
        sa.UniqueConstraint(
            "organization_id", "step_id", "user_id", name="uq_workflow_step_recipient"
        ),
    )
    op.create_index(
        "ix_workflow_recipient_inbox",
        "workflow_recipients",
        ["organization_id", "workspace_id", "user_id", "instance_id", "step_id"],
        unique=False,
    )
    op.create_index(
        "uq_workflow_active_form",
        "workflow_versions",
        ["organization_id", "workspace_id", "form_version_id"],
        unique=True,
        postgresql_where=sa.text("state='active'"),
    )
    op.execute("""
    CREATE FUNCTION protect_workflow_runtime() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE node jsonb; votes integer; recipients integer; required_votes integer;
    BEGIN
      IF TG_OP IN ('DELETE','TRUNCATE') THEN
        RAISE EXCEPTION 'Workflow history cannot be deleted' USING ERRCODE='55000';
      END IF;
      IF TG_OP='UPDATE' THEN
        IF TG_TABLE_NAME='workflow_instances' THEN
          IF OLD.state <> 'active' OR NEW.revision <> OLD.revision+1 OR
            (to_jsonb(NEW)-ARRAY['state','current_node','revision']) IS DISTINCT FROM
            (to_jsonb(OLD)-ARRAY['state','current_node','revision']) THEN
            RAISE EXCEPTION 'Invalid workflow instance transition' USING ERRCODE='55000';
          END IF;
        ELSIF TG_TABLE_NAME='workflow_steps' THEN
          IF OLD.state <> 'open' OR NEW.state='open' OR
            (to_jsonb(NEW)-'state') IS DISTINCT FROM (to_jsonb(OLD)-'state') THEN
            RAISE EXCEPTION 'Workflow visit is immutable' USING ERRCODE='55000';
          END IF;
          IF NEW.state='completed' THEN
            SELECT n INTO node FROM workflow_instances i
              JOIN workflow_versions v ON v.id=i.workflow_version_id,
              LATERAL jsonb_array_elements(v.definition->'nodes') n
              WHERE i.id=NEW.instance_id AND n->>'key'=NEW.node_key;
            SELECT count(*) INTO recipients FROM workflow_recipients r WHERE r.step_id=NEW.id;
            SELECT count(*) INTO votes FROM workflow_actions a WHERE a.step_id=NEW.id
              AND a.kind=CASE WHEN node->>'kind'='approval' THEN 'approve' ELSE 'review' END;
            required_votes := CASE node->'policy'->>'mode'
              WHEN 'one' THEN 1 WHEN 'quorum' THEN (node->'policy'->>'quorum')::integer
              ELSE recipients END;
            IF required_votes IS NULL OR required_votes<1 OR votes<required_votes THEN
              RAISE EXCEPTION 'Workflow completion policy not satisfied' USING ERRCODE='55000';
            END IF;
          ELSE
            IF NOT EXISTS(SELECT 1 FROM workflow_actions a WHERE a.step_id=NEW.id
              AND a.kind=CASE WHEN NEW.state='returned' THEN 'return' ELSE 'reject' END) THEN
              RAISE EXCEPTION 'Workflow decision evidence required' USING ERRCODE='55000';
            END IF;
          END IF;
        ELSE
          RAISE EXCEPTION 'Workflow evidence is immutable' USING ERRCODE='55000';
        END IF;
      END IF;
      IF TG_OP='INSERT' AND TG_TABLE_NAME='workflow_instances' THEN
        IF NOT EXISTS(SELECT 1 FROM submissions s JOIN workflow_versions v
          ON v.id=NEW.workflow_version_id WHERE s.id=NEW.submission_id
          AND s.organization_id=NEW.organization_id AND s.workspace_id=NEW.workspace_id
          AND s.owner_id=NEW.owner_id AND s.state='submitted'
          AND s.form_version_id=v.form_version_id AND v.state='active') THEN
          RAISE EXCEPTION 'Submitted workflow snapshot required' USING ERRCODE='55000';
        END IF;
      END IF;
      IF TG_OP='INSERT' AND TG_TABLE_NAME='workflow_actions' THEN
        SELECT n INTO node FROM workflow_steps st
          JOIN workflow_instances i ON i.id=st.instance_id
          JOIN workflow_versions v ON v.id=i.workflow_version_id,
          LATERAL jsonb_array_elements(v.definition->'nodes') n
          WHERE st.id=NEW.step_id AND st.state='open' AND i.state='active'
          AND i.current_node=st.node_key AND n->>'key'=st.node_key;
        IF node IS NULL OR NOT EXISTS(SELECT 1 FROM workflow_recipients r
          WHERE r.step_id=NEW.step_id AND r.user_id=NEW.actor_id) THEN
          RAISE EXCEPTION 'Open assigned workflow step required' USING ERRCODE='55000';
        END IF;
        IF NEW.kind IN ('approve','review') AND NEW.kind <> (CASE
          WHEN node->>'kind'='approval' THEN 'approve' ELSE 'review' END) THEN
          RAISE EXCEPTION 'Wrong workflow action kind' USING ERRCODE='55000';
        END IF;
        IF NEW.kind='approve' AND EXISTS(SELECT 1 FROM workflow_instances i
          WHERE i.id=NEW.instance_id AND i.owner_id=NEW.actor_id) THEN
          RAISE EXCEPTION 'Independent approval required' USING ERRCODE='55000';
        END IF;
        IF NEW.kind IN ('approve','review') AND node->'policy'->>'mode'='sequential' THEN
          SELECT count(*) INTO votes FROM workflow_actions a WHERE a.step_id=NEW.step_id;
          IF NOT EXISTS(SELECT 1 FROM workflow_recipients r WHERE r.step_id=NEW.step_id
            AND r.user_id=NEW.actor_id AND r.position=votes) THEN
            RAISE EXCEPTION 'Sequential approval order required' USING ERRCODE='55000';
          END IF;
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    """)
    for table in (
        "workflow_instances",
        "workflow_steps",
        "workflow_recipients",
        "workflow_actions",
        "workflow_notifications",
    ):
        op.execute(
            f"CREATE TRIGGER protect_{table} BEFORE INSERT OR UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_workflow_runtime()"
        )
        op.execute(
            f"CREATE TRIGGER protect_{table}_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION protect_workflow_runtime()"
        )


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS(SELECT 1 FROM workflow_instances) OR EXISTS(SELECT 1 FROM workflow_steps)
        OR EXISTS(SELECT 1 FROM workflow_recipients) OR EXISTS(SELECT 1 FROM workflow_actions)
        OR EXISTS(SELECT 1 FROM workflow_notifications) THEN
        RAISE EXCEPTION 'Populated workflow runtime downgrade refused; restore/reconcile backup'
          USING ERRCODE='55000';
      END IF;
    END $$;
    DROP FUNCTION protect_workflow_runtime() CASCADE;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_workflow_active_form",
        table_name="workflow_versions",
        postgresql_where=sa.text("state='active'"),
    )
    op.drop_index("ix_workflow_recipient_inbox", table_name="workflow_recipients")
    op.drop_table("workflow_recipients")
    op.drop_index("ix_workflow_action_history", table_name="workflow_actions")
    op.drop_table("workflow_actions")
    op.drop_index("ix_workflow_step_instance", table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index("ix_workflow_notification_cursor", table_name="workflow_notifications")
    op.drop_table("workflow_notifications")
    op.drop_index("ix_workflow_instance_scope_cursor", table_name="workflow_instances")
    op.drop_table("workflow_instances")
    # ### end Alembic commands ###
