"""phase 6 durable scoped email ledger"""

import sqlalchemy as sa
from alembic import op

revision = "208f826ca492"
down_revision = "e18c49c4be63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=True),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.CheckConstraint(
            "(source_kind='invitation' AND recipient_id IS NULL) OR "
            "(source_kind='notice' AND recipient_id IS NOT NULL)",
            name=op.f("ck_email_deliveries_source"),
        ),
        sa.CheckConstraint(
            "state IN ('pending','sending','sent','retry','uncertain','failed','skipped')",
            name=op.f("ck_email_deliveries_state"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 20", name=op.f("ck_email_deliveries_attempt_bound")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recipient_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_email_deliveries_organization_id_users_recipient"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "operator_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_email_deliveries_organization_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_deliveries")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_email_deliveries_organization_id")
        ),
    )
    op.create_index(
        "ix_email_due",
        "email_deliveries",
        ["organization_id", "state", "next_at", "id"],
        unique=False,
    )
    op.create_table(
        "email_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('sent','retry','uncertain','failed','skipped')",
            name=op.f("ck_email_attempts_outcome"),
        ),
        sa.CheckConstraint("number BETWEEN 1 AND 20", name=op.f("ck_email_attempts_attempt_bound")),
        sa.ForeignKeyConstraint(
            ["organization_id", "delivery_id"],
            ["email_deliveries.organization_id", "email_deliveries.id"],
            name=op.f("fk_email_attempts_organization_id_email_deliveries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_attempts")),
        sa.UniqueConstraint(
            "organization_id",
            "delivery_id",
            "number",
            name=op.f("uq_email_attempts_organization_id"),
        ),
    )
    op.create_index(
        "uq_email_invitation_source",
        "email_deliveries",
        ["organization_id", "source_id"],
        unique=True,
        postgresql_where=sa.text("source_kind='invitation'"),
    )
    op.create_index(
        "uq_email_notice_source",
        "email_deliveries",
        ["organization_id", "source_id", "recipient_id"],
        unique=True,
        postgresql_where=sa.text("source_kind='notice'"),
    )
    op.execute("""
      CREATE FUNCTION guard_email_delivery() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF TG_OP <> 'UPDATE' THEN RAISE EXCEPTION 'Email evidence cannot be removed'; END IF;
        IF (to_jsonb(NEW) - ARRAY['state','attempts','next_at','error_code']) IS DISTINCT FROM
           (to_jsonb(OLD) - ARRAY['state','attempts','next_at','error_code']) THEN
          RAISE EXCEPTION 'Email source binding is immutable';
        END IF;
        IF NOT (
          (OLD.state IN ('pending','retry') AND NEW.state='sending'
           AND NEW.attempts=OLD.attempts+1) OR
          (OLD.state='sending' AND NEW.state IN ('sent','retry','failed','uncertain','skipped')
           AND NEW.attempts=OLD.attempts) OR
          (OLD.state IN ('retry','failed','uncertain') AND NEW.state='retry'
           AND NEW.attempts=OLD.attempts)
        ) THEN RAISE EXCEPTION 'Invalid email transition'; END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER guard_email_delivery BEFORE UPDATE OR DELETE ON email_deliveries
        FOR EACH ROW EXECUTE FUNCTION guard_email_delivery();
      CREATE TRIGGER guard_email_delivery_truncate BEFORE TRUNCATE ON email_deliveries
        FOR EACH STATEMENT EXECUTE FUNCTION guard_email_delivery();
      CREATE FUNCTION guard_email_attempt() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Email attempts are immutable'; END IF;
        IF NOT EXISTS (SELECT 1 FROM email_deliveries d WHERE d.organization_id=NEW.organization_id
          AND d.id=NEW.delivery_id AND d.attempts=NEW.number AND d.state=NEW.outcome) THEN
          RAISE EXCEPTION 'Email attempt does not match its delivery';
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER guard_email_attempt BEFORE INSERT OR UPDATE OR DELETE ON email_attempts
        FOR EACH ROW EXECUTE FUNCTION guard_email_attempt();
      CREATE TRIGGER guard_email_attempt_truncate BEFORE TRUNCATE ON email_attempts
        FOR EACH STATEMENT EXECUTE FUNCTION guard_email_attempt();
    """)


def downgrade() -> None:
    if op.get_bind().scalar(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM email_deliveries) OR "
            "EXISTS (SELECT 1 FROM email_attempts)"
        )
    ):
        raise RuntimeError("Email evidence exists; forward fix or verified restore required")
    op.execute("DROP TRIGGER guard_email_attempt_truncate ON email_attempts")
    op.execute("DROP TRIGGER guard_email_attempt ON email_attempts")
    op.execute("DROP FUNCTION guard_email_attempt()")
    op.execute("DROP TRIGGER guard_email_delivery_truncate ON email_deliveries")
    op.execute("DROP TRIGGER guard_email_delivery ON email_deliveries")
    op.execute("DROP FUNCTION guard_email_delivery()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_attempts")
    op.drop_index("ix_email_due", table_name="email_deliveries")
    op.drop_table("email_deliveries")
    # ### end Alembic commands ###
