"""phase 6 historical notification handoff indexes"""

import sqlalchemy as sa
from alembic import op

revision = "34e34c3ce85a"
down_revision = "a5fa16a227ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_outbox_aggregate_lookup",
        "outbox_events",
        [
            "organization_id",
            "workspace_id",
            "type",
            sa.literal_column("(envelope ->> 'aggregate_id')"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_task_reminders_workspace_cursor",
        "task_reminders",
        ["organization_id", "workspace_id", "id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_notification_workspace_cursor",
        "workflow_notifications",
        ["organization_id", "workspace_id", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_notification_workspace_cursor", table_name="workflow_notifications")
    op.drop_index("ix_task_reminders_workspace_cursor", table_name="task_reminders")
    op.drop_index("ix_outbox_aggregate_lookup", table_name="outbox_events")
    # ### end Alembic commands ###
