"""phase 3 versioned forms submissions and private files"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "464245e2e729"
down_revision = "4c982bc7d8c5"
branch_labels = None
depends_on = None

TABLES = ("forms", "form_versions", "form_library_artifacts", "submissions", "files")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_library_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "kind IN ('field', 'component', 'form') AND version > 0",
            name=op.f("ck_form_library_artifacts_library_kind_version"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_form_library_artifacts_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_library_artifacts")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "code", "version", name="uq_form_library_version"
        ),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", "version", name="uq_form_library_pin"
        ),
    )
    op.create_index(
        "ix_form_library_cursor",
        "form_library_artifacts",
        ["organization_id", "workspace_id", "id"],
        unique=False,
    )
    op.create_table(
        "forms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_forms_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_forms_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forms")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_forms_scope_identity"
        ),
    )
    op.create_index(
        "ix_forms_scope_cursor",
        "forms",
        ["organization_id", "workspace_id", "project_id", "id"],
        unique=False,
    )
    op.create_table(
        "form_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "(state = 'draft' AND published_at IS NULL AND content_sha256 IS NULL) OR "
            "(state <> 'draft' AND published_at IS NOT NULL AND content_sha256 IS NOT NULL)",
            name=op.f("ck_form_versions_form_publication_snapshot"),
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'deprecated', 'retired')",
            name=op.f("ck_form_versions_form_state"),
        ),
        sa.CheckConstraint(
            "number > 0 AND revision > 0", name=op.f("ck_form_versions_form_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "form_id"],
            ["forms.organization_id", "forms.workspace_id", "forms.id"],
            name=op.f("fk_form_versions_organization_id_forms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_versions")),
        sa.UniqueConstraint("organization_id", "form_id", "number", name="uq_form_versions_number"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "form_id",
            "id",
            "number",
            name="uq_form_versions_exact_identity",
        ),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_form_versions_scope_identity"
        ),
    )
    op.create_index(
        "ix_form_versions_cursor",
        "form_versions",
        ["organization_id", "form_id", "id"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("form_version_id", sa.Uuid(), nullable=False),
        sa.Column("form_number", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submit_key", sa.Uuid(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("signatures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(state='draft' AND submitted_at IS NULL AND submit_key IS NULL "
            "AND content_sha256 IS NULL) OR "
            "(state='submitted' AND submitted_at IS NOT NULL AND submit_key IS NOT NULL "
            "AND content_sha256 IS NOT NULL)",
            name=op.f("ck_submissions_submission_snapshot"),
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'submitted') AND revision > 0 AND form_number > 0",
            name=op.f("ck_submissions_submission_lifecycle"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_submissions_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "form_id", "form_version_id", "form_number"],
            [
                "form_versions.organization_id",
                "form_versions.workspace_id",
                "form_versions.form_id",
                "form_versions.id",
                "form_versions.number",
            ],
            name=op.f("fk_submissions_organization_id_form_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "form_id"],
            ["forms.organization_id", "forms.workspace_id", "forms.id"],
            name=op.f("fk_submissions_organization_id_forms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
        sa.UniqueConstraint("organization_id", "submit_key", name="uq_submissions_submit_key"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_submissions_scope_identity"
        ),
    )
    op.create_index(
        "ix_submissions_scope_owner_cursor",
        "submissions",
        ["organization_id", "workspace_id", "form_id", "owner_id", "id"],
        unique=False,
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("content_type", sa.String(length=60), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=240), nullable=False),
        sa.CheckConstraint("size > 0 AND size <= 5242880", name=op.f("ck_files_attachment_size")),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_files_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "submission_id"],
            ["submissions.organization_id", "submissions.workspace_id", "submissions.id"],
            name=op.f("fk_files_organization_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("object_key", name=op.f("uq_files_object_key")),
    )
    op.create_index(
        "ix_files_scope_submission",
        "files",
        ["organization_id", "workspace_id", "submission_id", "id"],
        unique=False,
    )
    op.execute("""
        CREATE FUNCTION protect_phase3_record() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION 'Form operational history cannot be removed' USING ERRCODE='55000';
            END IF;
            IF TG_TABLE_NAME IN ('form_library_artifacts', 'files') THEN
                RAISE EXCEPTION 'Artifact and file identities are immutable' USING ERRCODE='55000';
            ELSIF TG_TABLE_NAME = 'form_versions' THEN
                IF (OLD.id, OLD.organization_id, OLD.workspace_id, OLD.form_id, OLD.number)
                   IS DISTINCT FROM (NEW.id, NEW.organization_id, NEW.workspace_id,
                                        NEW.form_id, NEW.number)
                   OR NEW.revision <> OLD.revision + 1 THEN
                    RAISE EXCEPTION 'Form version identity/revision is invalid'
                        USING ERRCODE='55000';
                END IF;
                IF OLD.state <> 'draft' THEN
                    IF (OLD.definition, OLD.published_at, OLD.content_sha256) IS DISTINCT FROM
                       (NEW.definition, NEW.published_at, NEW.content_sha256)
                       OR NOT ((OLD.state='published' AND NEW.state IN ('deprecated','retired'))
                            OR (OLD.state='deprecated' AND NEW.state='retired')) THEN
                        RAISE EXCEPTION 'Published form version is immutable' USING ERRCODE='55000';
                    END IF;
                ELSIF NEW.state NOT IN ('draft','published') THEN
                    RAISE EXCEPTION 'Invalid publication transition' USING ERRCODE='55000';
                END IF;
            ELSIF TG_TABLE_NAME = 'submissions' THEN
                IF OLD.state='submitted' THEN
                    RAISE EXCEPTION 'Submitted snapshot is immutable' USING ERRCODE='55000';
                END IF;
                IF (OLD.id, OLD.organization_id, OLD.workspace_id, OLD.form_id, OLD.form_version_id,
                    OLD.form_number, OLD.owner_id) IS DISTINCT FROM
                   (NEW.id, NEW.organization_id, NEW.workspace_id, NEW.form_id, NEW.form_version_id,
                    NEW.form_number, NEW.owner_id) OR NEW.revision <> OLD.revision + 1 THEN
                    RAISE EXCEPTION 'Submission identity/revision is invalid' USING ERRCODE='55000';
                END IF;
            ELSIF (OLD.id, OLD.organization_id, OLD.workspace_id, OLD.project_id) IS DISTINCT FROM
                  (NEW.id, NEW.organization_id, NEW.workspace_id, NEW.project_id) THEN
                RAISE EXCEPTION 'Form ownership is immutable' USING ERRCODE='55000';
            END IF;
            RETURN NEW;
        END $$
    """)
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER preserve_form_history BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_phase3_record()"
        )
        op.execute(
            f"CREATE TRIGGER preserve_form_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION protect_phase3_record()"
        )


def downgrade() -> None:
    for table in TABLES:
        if op.get_bind().scalar(sa.text(f"SELECT EXISTS (SELECT 1 FROM {table} LIMIT 1)")):
            raise RuntimeError(
                "Refusing populated Phase 3 downgrade; preserve history and restore/reconcile"
            )
    for table in TABLES:
        op.execute(f"DROP TRIGGER preserve_form_history ON {table}")
        op.execute(f"DROP TRIGGER preserve_form_truncate ON {table}")
    op.execute("DROP FUNCTION protect_phase3_record()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_files_scope_submission", table_name="files")
    op.drop_table("files")
    op.drop_index("ix_submissions_scope_owner_cursor", table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("ix_form_versions_cursor", table_name="form_versions")
    op.drop_table("form_versions")
    op.drop_index("ix_forms_scope_cursor", table_name="forms")
    op.drop_table("forms")
    op.drop_index("ix_form_library_cursor", table_name="form_library_artifacts")
    op.drop_table("form_library_artifacts")
    # ### end Alembic commands ###
