"""phase 6 immutable in app notifications"""

import sqlalchemy as sa
from alembic import op

revision = "73eddd554d17"
down_revision = "a39df7b251c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=30), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 19 "
            "AND topic IN ('work_assigned','review_requested','rule_notice') "
            "AND source_kind IN ('task','workflow','submission','project')",
            name=op.f("ck_notifications_notice_contract"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "event_id"],
            ["outbox_events.organization_id", "outbox_events.id"],
            name=op.f("fk_notifications_organization_id_outbox_events"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recipient_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_notifications_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["automation_runs.organization_id", "automation_runs.id"],
            name=op.f("fk_notifications_organization_id_automation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_notifications_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_notifications_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("organization_id", "id", "recipient_id", name="uq_notice_recipient"),
        sa.UniqueConstraint(
            "organization_id", "run_id", "position", "recipient_id", name="uq_notice_action_once"
        ),
    )
    op.create_index(
        "ix_notice_recipient_cursor",
        "notifications",
        ["organization_id", "workspace_id", "recipient_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "notification_reads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("notice_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "notice_id", "recipient_id"],
            ["notifications.organization_id", "notifications.id", "notifications.recipient_id"],
            name=op.f("fk_notification_reads_organization_id_notifications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_reads")),
        sa.UniqueConstraint("organization_id", "notice_id", name="uq_notice_read_once"),
    )
    # ### end Alembic commands ###
    install_guards()


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS(SELECT 1 FROM notifications) OR EXISTS(SELECT 1 FROM notification_reads)
      THEN RAISE EXCEPTION 'Populated notification downgrade refused; preserve evidence'
        USING ERRCODE='55000'; END IF;
    END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_reads")
    op.drop_index("ix_notice_recipient_cursor", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION notification_insert_guard()")
    op.execute("DROP FUNCTION notification_read_guard()")


def install_guards() -> None:
    op.execute("""
    CREATE FUNCTION notification_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM automation_runs r
        JOIN outbox_events e ON e.id=r.event_id AND e.organization_id=r.organization_id
        JOIN automation_versions v ON v.id=r.rule_version_id AND v.organization_id=r.organization_id
        WHERE r.id=NEW.run_id AND r.organization_id=NEW.organization_id
          AND r.event_id=NEW.event_id AND r.state IN ('pending','retry')
          AND e.workspace_id=NEW.workspace_id AND e.project_id IS NOT DISTINCT FROM NEW.project_id
          AND v.definition->'actions'->NEW.position->>'kind'='notify'
          AND v.definition->'actions'->NEW.position->'channels'='["in_app"]'::jsonb
          AND v.definition->'actions'->NEW.position->'recipients'
              @> to_jsonb(NEW.recipient_id::text)
          AND v.definition->'actions'->NEW.position->>'topic'=NEW.topic
          AND NEW.created_at >= e.occurred_at
          AND ((NEW.source_kind='task'
                AND e.envelope->'payload'->>'task_id'=NEW.source_id::text)
            OR (NEW.source_kind='workflow' AND e.envelope->'payload'->>'task_id' IS NULL
                AND e.envelope->'payload'->>'workflow_instance_id'=NEW.source_id::text)
            OR (NEW.source_kind='submission' AND e.envelope->'payload'->>'task_id' IS NULL
                AND e.envelope->'payload'->>'workflow_instance_id' IS NULL
                AND e.envelope->'payload'->>'submission_id'=NEW.source_id::text)
            OR (NEW.source_kind='project' AND e.envelope->>'aggregate_type'='project'
                AND e.envelope->>'aggregate_id'=NEW.source_id::text
                AND e.project_id=NEW.source_id))
          AND (NEW.topic='rule_notice' OR (NEW.topic='work_assigned' AND NEW.source_kind='task')
            OR (NEW.topic='review_requested' AND NEW.source_kind='workflow'))
          AND EXISTS (SELECT 1 FROM audit_events a WHERE a.organization_id=NEW.organization_id
            AND a.aggregate_id=NEW.id AND a.type='notification.created'
            AND a.payload->>'run_id'=NEW.run_id::text
            AND a.payload->>'target_id'=NEW.recipient_id::text
            AND a.payload->>'workspace_id'=NEW.workspace_id::text)
      ) THEN RAISE EXCEPTION 'Invalid notification source/action evidence'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER notifications_insert_guard BEFORE INSERT ON notifications
      FOR EACH ROW EXECUTE FUNCTION notification_insert_guard();
    CREATE FUNCTION notification_read_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM notifications n JOIN audit_events a
          ON a.organization_id=n.organization_id AND a.aggregate_id=n.id
        WHERE n.organization_id=NEW.organization_id AND n.id=NEW.notice_id
          AND n.recipient_id=NEW.recipient_id AND NEW.read_at >= n.created_at
          AND a.type='notification.read' AND a.actor_id=NEW.recipient_id
          AND a.payload->>'target_id'=NEW.recipient_id::text)
      THEN RAISE EXCEPTION 'Invalid notification read evidence' USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER notification_reads_insert_guard BEFORE INSERT ON notification_reads
      FOR EACH ROW EXECUTE FUNCTION notification_read_guard();
    """)
    for table in ("notifications", "notification_reads"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION automation_no_rewrite()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION automation_no_rewrite()"
        )
