"""phase 6 durable outbox and delegated automation ledger"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "8323b0dbac0e"
down_revision = "71db385e7a02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active_number", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_automation_rules_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_automation_rules_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_rules")),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "id",
            name=op.f("uq_automation_rules_organization_id"),
        ),
    )
    op.create_index(
        "ix_automation_rule_scope",
        "automation_rules",
        ["organization_id", "workspace_id", "project_id", "id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "project_id IS NULL OR workspace_id IS NOT NULL",
            name=op.f("ck_outbox_events_outbox_project_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_outbox_events_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_outbox_events_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_outbox_events_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_outbox_events_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_outbox_events_organization_id")),
    )
    op.create_index(
        "ix_outbox_scope_cursor",
        "outbox_events",
        ["organization_id", "workspace_id", "id"],
        unique=False,
    )
    op.create_table(
        "automation_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("activator_id", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "number>0 AND revision>0 AND ((state='draft' AND activator_id IS NULL "
            "AND activated_at IS NULL AND content_sha256 IS NULL) OR "
            "(state IN ('active','retired') AND activator_id IS NOT NULL "
            "AND activated_at IS NOT NULL AND length(content_sha256)=64))",
            name=op.f("ck_automation_versions_automation_version_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "activator_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_automation_versions_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "rule_id"],
            [
                "automation_rules.organization_id",
                "automation_rules.workspace_id",
                "automation_rules.id",
            ],
            name=op.f("fk_automation_versions_organization_id_automation_rules"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_versions")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_automation_versions_organization_id")
        ),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "rule_id", "number", name="uq_rule_version_number"
        ),
    )
    op.create_index(
        "uq_automation_active_rule",
        "automation_versions",
        ["organization_id", "rule_id"],
        unique=True,
        postgresql_where=sa.text("state='active'"),
    )
    op.create_table(
        "outbox_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("consumer", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "consumer IN ('automation','notifications') AND "
            "state IN ('pending','dispatched','completed','retry','dead_letter') "
            "AND attempts BETWEEN 0 AND 20",
            name=op.f("ck_outbox_deliveries_delivery_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "event_id"],
            ["outbox_events.organization_id", "outbox_events.id"],
            name=op.f("fk_outbox_deliveries_organization_id_outbox_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_deliveries")),
        sa.UniqueConstraint("organization_id", "event_id", "consumer", name="uq_delivery_consumer"),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_outbox_deliveries_organization_id")
        ),
    )
    op.create_index(
        "ix_delivery_due",
        "outbox_deliveries",
        ["organization_id", "state", "next_at", "id"],
        unique=False,
    )
    op.create_table(
        "automation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_version_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("delegator_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_actor_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending','completed','skipped','retry','dead_letter') "
            "AND attempts BETWEEN 0 AND 20",
            name=op.f("ck_automation_runs_automation_run_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "delegator_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_automation_runs_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "event_id"],
            ["outbox_events.organization_id", "outbox_events.id"],
            name=op.f("fk_automation_runs_organization_id_outbox_events"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "rule_version_id"],
            ["automation_versions.organization_id", "automation_versions.id"],
            name=op.f("fk_automation_runs_organization_id_automation_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_automation_runs_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_runs")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_automation_runs_organization_id")
        ),
        sa.UniqueConstraint(
            "organization_id", "rule_version_id", "event_id", name="uq_run_event_version"
        ),
    )
    op.create_index(
        "ix_automation_run_scope",
        "automation_runs",
        ["organization_id", "workspace_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "automation_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "number BETWEEN 1 AND 20 AND finished_at>=started_at AND "
            "outcome IN ('completed','skipped','retry','dead_letter')",
            name=op.f("ck_automation_attempts_attempt_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["automation_runs.organization_id", "automation_runs.id"],
            name=op.f("fk_automation_attempts_organization_id_automation_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_attempts")),
        sa.UniqueConstraint(
            "organization_id",
            "run_id",
            "number",
            name=op.f("uq_automation_attempts_organization_id"),
        ),
    )
    op.create_table(
        "automation_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 19",
            name=op.f("ck_automation_receipts_automation_receipt_position"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["automation_runs.organization_id", "automation_runs.id"],
            name=op.f("fk_automation_receipts_organization_id_automation_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_receipts")),
        sa.UniqueConstraint(
            "organization_id",
            "run_id",
            "position",
            name=op.f("uq_automation_receipts_organization_id"),
        ),
    )
    install_guards()


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS(SELECT 1 FROM automation_rules) OR EXISTS(SELECT 1 FROM outbox_events)
        OR EXISTS(SELECT 1 FROM automation_versions) OR EXISTS(SELECT 1 FROM automation_runs)
        OR EXISTS(SELECT 1 FROM automation_attempts) OR EXISTS(SELECT 1 FROM automation_receipts)
        OR EXISTS(SELECT 1 FROM outbox_deliveries)
      THEN RAISE EXCEPTION 'Populated Phase 6 downgrade refused; retain event and execution history'
        USING ERRCODE='55000'; END IF;
    END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("automation_receipts")
    op.drop_table("automation_attempts")
    op.drop_index("ix_automation_run_scope", table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index("ix_delivery_due", table_name="outbox_deliveries")
    op.drop_table("outbox_deliveries")
    op.drop_index(
        "uq_automation_active_rule",
        table_name="automation_versions",
        postgresql_where=sa.text("state='active'"),
    )
    op.drop_table("automation_versions")
    op.drop_index("ix_outbox_scope_cursor", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_automation_rule_scope", table_name="automation_rules")
    op.drop_table("automation_rules")
    for function in (
        "automation_no_rewrite",
        "automation_version_guard",
        "automation_rule_guard",
        "automation_run_guard",
        "automation_delivery_guard",
        "outbox_envelope_guard",
    ):
        op.execute(f"DROP FUNCTION {function}()")
    # ### end Alembic commands ###


def install_guards() -> None:
    op.execute("""
    CREATE FUNCTION automation_no_rewrite() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'Automation evidence is immutable' USING ERRCODE='55000'; END $$;

    CREATE FUNCTION outbox_envelope_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.envelope->>'id' IS DISTINCT FROM NEW.id::text
         OR NEW.envelope->>'organization_id' IS DISTINCT FROM NEW.organization_id::text
         OR NEW.envelope->>'workspace_id' IS DISTINCT FROM NEW.workspace_id::text
         OR NEW.envelope->>'project_id' IS DISTINCT FROM NEW.project_id::text
         OR NEW.envelope->>'actor_id' IS DISTINCT FROM NEW.actor_id::text
         OR NEW.envelope->>'type' IS DISTINCT FROM NEW.type
         OR (NEW.envelope->>'occurred_at')::timestamptz IS DISTINCT FROM NEW.occurred_at
      THEN RAISE EXCEPTION 'Outbox envelope does not match indexed identity'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION automation_version_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='INSERT' THEN
        IF NEW.state<>'draft' OR NEW.revision<>1 THEN
          RAISE EXCEPTION 'Automation versions must begin as drafts' USING ERRCODE='23514';
        END IF;
      ELSE
        IF ROW(NEW.id,NEW.organization_id,NEW.workspace_id,NEW.rule_id,NEW.number)
           IS DISTINCT FROM ROW(OLD.id,OLD.organization_id,OLD.workspace_id,OLD.rule_id,OLD.number)
           OR NEW.revision<>OLD.revision+1
           OR OLD.state='retired'
           OR (OLD.state='active' AND (NEW.state<>'retired'
               OR ROW(NEW.definition,NEW.activator_id,NEW.activated_at,NEW.content_sha256)
               IS DISTINCT FROM ROW(OLD.definition,OLD.activator_id,
                                    OLD.activated_at,OLD.content_sha256)))
           OR (OLD.state='draft' AND NEW.state NOT IN ('draft','active'))
           OR (OLD.state='draft' AND NEW.state='active'
               AND NEW.definition IS DISTINCT FROM OLD.definition)
        THEN RAISE EXCEPTION 'Invalid or immutable automation version transition'
          USING ERRCODE='55000'; END IF;
      END IF;
      IF NEW.state='active' AND NEW.definition->>'form_id' IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM forms f JOIN form_versions v ON v.form_id=f.id
          AND v.organization_id=f.organization_id AND v.workspace_id=f.workspace_id
        JOIN automation_rules r ON r.id=NEW.rule_id AND r.organization_id=NEW.organization_id
        WHERE f.id=(NEW.definition->>'form_id')::uuid AND f.organization_id=NEW.organization_id
          AND f.workspace_id=NEW.workspace_id AND f.project_id IS NOT DISTINCT FROM r.project_id
          AND v.number=(NEW.definition->>'form_number')::integer AND v.state='published'
      ) THEN RAISE EXCEPTION 'Automation form pin scope or state invalid'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION automation_rule_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='INSERT' THEN
        IF NEW.revision<>1 OR NEW.active_number IS NOT NULL THEN
          RAISE EXCEPTION 'Rules must begin without activation' USING ERRCODE='23514'; END IF;
      ELSE
        IF ROW(NEW.id,NEW.organization_id,NEW.workspace_id,NEW.project_id)
           IS DISTINCT FROM ROW(OLD.id,OLD.organization_id,OLD.workspace_id,OLD.project_id)
           OR NEW.revision<>OLD.revision+1 THEN
          RAISE EXCEPTION 'Automation identity or revision changed' USING ERRCODE='55000'; END IF;
      END IF;
      IF NEW.active_number IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM automation_versions WHERE organization_id=NEW.organization_id
          AND workspace_id=NEW.workspace_id AND rule_id=NEW.id AND number=NEW.active_number
          AND state='active'
      ) THEN RAISE EXCEPTION 'Automation active binding invalid' USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION automation_run_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='INSERT' THEN
        IF NEW.state<>'pending' OR NEW.attempts<>0 OR NEW.completed_at IS NOT NULL OR NOT EXISTS (
          SELECT 1 FROM automation_versions v
          JOIN automation_rules r ON r.id=v.rule_id AND r.organization_id=v.organization_id
          JOIN outbox_events e ON e.id=NEW.event_id AND e.organization_id=NEW.organization_id
          WHERE v.id=NEW.rule_version_id AND v.organization_id=NEW.organization_id
            AND v.workspace_id=NEW.workspace_id AND v.state='active'
            AND v.activator_id=NEW.delegator_id AND r.active_number=v.number
            AND e.workspace_id=NEW.workspace_id AND e.project_id IS NOT DISTINCT FROM r.project_id
            AND e.actor_id IS NOT DISTINCT FROM NEW.trigger_actor_id
            AND (e.envelope->>'correlation_id')::uuid=NEW.correlation_id
            AND e.type=v.definition->>'trigger'
            AND NOT (e.envelope->'causation_path' @> jsonb_build_array(v.id::text))
            AND jsonb_array_length(e.envelope->'causation_path')<16
            AND (v.definition->>'form_id' IS NULL OR
              (v.definition->>'form_id'=e.envelope->'payload'->>'form_id'
               AND v.definition->>'form_number'=e.envelope->'payload'->>'form_number'))
        ) THEN RAISE EXCEPTION 'Automation run delegation or source binding invalid'
          USING ERRCODE='23514'; END IF;
      ELSE
        IF ROW(NEW.id,NEW.organization_id,NEW.workspace_id,NEW.rule_version_id,NEW.event_id,
               NEW.delegator_id,NEW.trigger_actor_id,NEW.correlation_id,NEW.created_at)
           IS DISTINCT FROM ROW(OLD.id,OLD.organization_id,OLD.workspace_id,OLD.rule_version_id,
               OLD.event_id,OLD.delegator_id,OLD.trigger_actor_id,OLD.correlation_id,OLD.created_at)
           OR OLD.state IN ('completed','skipped')
           OR NEW.attempts NOT BETWEEN OLD.attempts AND OLD.attempts+1
           OR (NEW.state IN ('completed','skipped') AND
              (NEW.attempts<>OLD.attempts+1 OR NEW.completed_at IS NULL))
        THEN RAISE EXCEPTION 'Automation run identity or transition invalid'
          USING ERRCODE='55000'; END IF;
      END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION automation_delivery_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF ROW(NEW.id,NEW.organization_id,NEW.event_id,NEW.consumer)
         IS DISTINCT FROM ROW(OLD.id,OLD.organization_id,OLD.event_id,OLD.consumer)
         OR NEW.attempts NOT BETWEEN OLD.attempts AND OLD.attempts+1
      THEN RAISE EXCEPTION 'Delivery identity or attempt history changed'
        USING ERRCODE='55000'; END IF;
      RETURN NEW;
    END $$;
    """)
    for table in (
        "automation_rules",
        "automation_versions",
        "automation_runs",
        "automation_attempts",
        "automation_receipts",
        "outbox_events",
        "outbox_deliveries",
    ):
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION automation_no_rewrite()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION automation_no_rewrite()"
        )
    for table in ("outbox_events", "automation_attempts", "automation_receipts"):
        op.execute(
            f"CREATE TRIGGER {table}_no_update BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION automation_no_rewrite()"
        )
    for table, operations, function in (
        ("outbox_events", "INSERT", "outbox_envelope_guard"),
        ("automation_versions", "INSERT OR UPDATE", "automation_version_guard"),
        ("automation_rules", "INSERT OR UPDATE", "automation_rule_guard"),
        ("automation_runs", "INSERT OR UPDATE", "automation_run_guard"),
        ("outbox_deliveries", "UPDATE", "automation_delivery_guard"),
    ):
        op.execute(
            f"CREATE TRIGGER {table}_guard BEFORE {operations} ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION {function}()"
        )
