"""phase 2 projects departments and governed master data"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "99e791752349"
down_revision = "34c1f0cc7d24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("lifecycle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_projects_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_projects_scope_identity"
        ),
    )
    op.create_index(
        "ix_projects_scope_state",
        "projects",
        ["organization_id", "workspace_id", "state", "id"],
        unique=False,
    )
    op.create_table(
        "workspace_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('department', 'team')", name=op.f("ck_workspace_groups_group_kind")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_workspace_groups_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_groups")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_workspace_groups_scope_identity"
        ),
    )
    op.create_index(
        "ix_workspace_groups_scope_active",
        "workspace_groups",
        ["organization_id", "workspace_id", "active", "id"],
        unique=False,
    )
    op.create_table(
        "department_project_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "role IN ('ProjectManager', 'Contributor', 'Viewer')",
            name=op.f("ck_department_project_grants_project_role"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from",
            name=op.f("ck_department_project_grants_validity_window"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "department_id"],
            [
                "workspace_groups.organization_id",
                "workspace_groups.workspace_id",
                "workspace_groups.id",
            ],
            name=op.f("fk_department_project_grants_organization_id_workspace_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_department_project_grants_organization_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department_project_grants")),
    )
    op.create_index(
        "ix_department_project_grants_scope",
        "department_project_grants",
        ["organization_id", "workspace_id", "department_id", "revoked"],
        unique=False,
    )
    op.create_table(
        "group_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("manager", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_group_memberships_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "group_id"],
            [
                "workspace_groups.organization_id",
                "workspace_groups.workspace_id",
                "workspace_groups.id",
            ],
            name=op.f("fk_group_memberships_organization_id_workspace_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_memberships")),
    )
    op.create_index(
        "ix_group_memberships_scope_user",
        "group_memberships",
        ["organization_id", "workspace_id", "user_id", "active"],
        unique=False,
    )
    op.create_table(
        "master_data_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("registry", sa.String(length=20), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(scope = 'global' AND organization_id IS NULL AND owner_id = "
            "'00000000-0000-0000-0000-000000000000' AND scope_id = owner_id AND "
            "workspace_id IS NULL AND project_id IS NULL) OR (organization_id IS NOT "
            "NULL AND owner_id = organization_id AND organization_id <> "
            "'00000000-0000-0000-0000-000000000000' AND ((scope = 'organization' AND "
            "scope_id = organization_id AND workspace_id IS NULL AND project_id IS NULL) "
            "OR (scope = 'workspace' AND workspace_id IS NOT NULL AND scope_id = "
            "workspace_id AND project_id IS NULL) OR (scope = 'project' AND workspace_id "
            "IS NOT NULL AND project_id IS NOT NULL AND scope_id = project_id)))",
            name=op.f("ck_master_data_types_data_type_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_master_data_types_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_master_data_types_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_master_data_types_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_data_types")),
        sa.UniqueConstraint("owner_id", "id", name="uq_master_data_types_owner_identity"),
        sa.UniqueConstraint("owner_id", "scope_id", "code", name="uq_master_data_types_scope_code"),
    )
    op.create_index(
        "ix_master_data_types_scope",
        "master_data_types",
        ["organization_id", "workspace_id", "project_id", "id"],
        unique=False,
    )
    op.create_table(
        "project_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "role IN ('ProjectManager', 'Contributor', 'Viewer')",
            name=op.f("ck_project_memberships_project_role"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from",
            name=op.f("ck_project_memberships_validity_window"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_project_memberships_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_project_memberships_organization_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_memberships")),
    )
    op.create_index(
        "ix_project_memberships_scope_user",
        "project_memberships",
        ["organization_id", "workspace_id", "user_id", "revoked"],
        unique=False,
    )
    op.create_table(
        "master_data_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("type_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(organization_id IS NULL AND owner_id = "
            "'00000000-0000-0000-0000-000000000000') OR (organization_id IS NOT NULL AND "
            "owner_id = organization_id AND organization_id <> "
            "'00000000-0000-0000-0000-000000000000')",
            name=op.f("ck_master_data_records_data_record_owner"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'deprecated')",
            name=op.f("ck_master_data_records_record_status"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from",
            name=op.f("ck_master_data_records_record_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_master_data_records_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "type_id"],
            ["master_data_types.owner_id", "master_data_types.id"],
            name=op.f("fk_master_data_records_owner_id_master_data_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_data_records")),
        sa.UniqueConstraint("owner_id", "type_id", "code", name="uq_master_data_records_type_code"),
    )
    op.create_index(
        "ix_master_data_records_scope_status",
        "master_data_records",
        ["organization_id", "type_id", "status", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    for table in (
        "projects",
        "workspace_groups",
        "group_memberships",
        "project_memberships",
        "department_project_grants",
        "master_data_types",
        "master_data_records",
    ):
        if connection.scalar(sa.text(f"SELECT EXISTS (SELECT 1 FROM {table} LIMIT 1)")):
            raise RuntimeError(
                "Refusing populated Phase 2 downgrade; restore verified backup or forward fix"
            )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_master_data_records_scope_status", table_name="master_data_records")
    op.drop_table("master_data_records")
    op.drop_index("ix_project_memberships_scope_user", table_name="project_memberships")
    op.drop_table("project_memberships")
    op.drop_index("ix_master_data_types_scope", table_name="master_data_types")
    op.drop_table("master_data_types")
    op.drop_index("ix_group_memberships_scope_user", table_name="group_memberships")
    op.drop_table("group_memberships")
    op.drop_index("ix_department_project_grants_scope", table_name="department_project_grants")
    op.drop_table("department_project_grants")
    op.drop_index("ix_workspace_groups_scope_active", table_name="workspace_groups")
    op.drop_table("workspace_groups")
    op.drop_index("ix_projects_scope_state", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
