"""phase 6 periodic timer and task deadline evidence"""

import sqlalchemy as sa
from alembic import op

revision = "a39df7b251c0"
down_revision = "8323b0dbac0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_timer_occurrences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_version_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_automation_timer_occurrences_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "id"],
            ["outbox_events.organization_id", "outbox_events.id"],
            name=op.f("fk_automation_timer_occurrences_organization_id_outbox_events"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "rule_version_id"],
            ["automation_versions.organization_id", "automation_versions.id"],
            name=op.f("fk_automation_timer_occurrences_organization_id_automation_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_timer_occurrences")),
        sa.UniqueConstraint(
            "organization_id", "rule_version_id", "scheduled_at", name="uq_timer_slot_once"
        ),
    )
    op.create_table(
        "task_deadline_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('due','overdue')", name=op.f("ck_task_deadline_events_deadline_kind")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "id"],
            ["outbox_events.organization_id", "outbox_events.id"],
            name=op.f("fk_task_deadline_events_organization_id_outbox_events"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "task_id"],
            [
                "task_occurrences.organization_id",
                "task_occurrences.workspace_id",
                "task_occurrences.id",
            ],
            name=op.f("fk_task_deadline_events_organization_id_task_occurrences"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_deadline_events")),
        sa.UniqueConstraint("organization_id", "task_id", "kind", name="uq_task_deadline_once"),
    )
    # ### end Alembic commands ###
    install_guards()


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS(SELECT 1 FROM automation_timer_occurrences)
        OR EXISTS(SELECT 1 FROM task_deadline_events)
      THEN RAISE EXCEPTION 'Populated periodic trigger downgrade refused; preserve evidence'
        USING ERRCODE='55000'; END IF;
    END $$;
    """)
    op.execute("DROP TRIGGER automation_periodic_run_guard ON automation_runs")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_deadline_events")
    op.drop_table("automation_timer_occurrences")
    # ### end Alembic commands ###
    for function in ("periodic_timer_guard", "periodic_deadline_guard", "periodic_run_guard"):
        op.execute(f"DROP FUNCTION {function}()")


def install_guards() -> None:
    op.execute("""
    CREATE FUNCTION periodic_deadline_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM task_occurrences t
        JOIN outbox_events e ON e.id=NEW.id AND e.organization_id=t.organization_id
        JOIN audit_events a ON a.id=e.id AND a.organization_id=e.organization_id
        WHERE t.id=NEW.task_id AND t.organization_id=NEW.organization_id
          AND t.workspace_id=NEW.workspace_id AND t.due_at=NEW.scheduled_at
          AND t.state IN ('open','in_progress','returned')
          AND e.workspace_id=t.workspace_id AND e.project_id IS NOT DISTINCT FROM t.project_id
          AND e.type='task.'||NEW.kind AND a.type=e.type AND a.aggregate_type='task'
          AND a.aggregate_id=t.id AND e.envelope->>'aggregate_id'=t.id::text
          AND e.envelope->>'aggregate_type'='task'
          AND e.envelope->'payload'->>'task_id'=t.id::text
          AND e.envelope->'payload'->>'form_id'=t.form_id::text
          AND (e.envelope->'payload'->>'form_number')::integer=t.form_number
          AND (e.envelope->'payload'->>'scheduled_at')::timestamptz=NEW.scheduled_at
          AND (a.payload->>'scheduled_at')::timestamptz=NEW.scheduled_at
          AND e.envelope->'payload'->>'submission_id' IS NULL
          AND ((NEW.kind='due' AND NEW.scheduled_at<=e.occurred_at)
               OR (NEW.kind='overdue' AND NEW.scheduled_at<e.occurred_at))
      ) THEN RAISE EXCEPTION 'Deadline source, scope or evidence invalid'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION periodic_timer_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM automation_versions v
        JOIN automation_rules r ON r.id=v.rule_id AND r.organization_id=v.organization_id
        JOIN outbox_events e ON e.id=NEW.id AND e.organization_id=v.organization_id
        JOIN audit_events a ON a.id=e.id AND a.organization_id=e.organization_id
        WHERE v.id=NEW.rule_version_id AND v.organization_id=NEW.organization_id
          AND v.workspace_id=NEW.workspace_id AND v.state='active' AND r.active_number=v.number
          AND v.definition->>'trigger'='scheduled.timer'
          AND NEW.scheduled_at>=v.activated_at AND NEW.scheduled_at<=e.occurred_at
          AND NEW.scheduled_at>=(v.definition->>'timer_start')::timestamptz
          AND mod(extract(epoch FROM
                    (NEW.scheduled_at-(v.definition->>'timer_start')::timestamptz)),
                  (v.definition->>'timer_seconds')::integer)=0
          AND e.workspace_id=v.workspace_id AND e.project_id IS NOT DISTINCT FROM r.project_id
          AND e.type='scheduled.timer' AND a.type='timer.fired' AND a.aggregate_type='timer'
          AND a.aggregate_id=v.id AND e.envelope->>'aggregate_type'='timer'
          AND e.envelope->>'aggregate_id'=v.id::text
          AND e.envelope->'payload'->>'timer_version_id'=v.id::text
          AND (e.envelope->'payload'->>'scheduled_at')::timestamptz=NEW.scheduled_at
          AND (a.payload->>'scheduled_at')::timestamptz=NEW.scheduled_at
      ) THEN RAISE EXCEPTION 'Timer source, activation, slot or evidence invalid'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION periodic_run_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF EXISTS(SELECT 1 FROM outbox_events WHERE id=NEW.event_id
                  AND organization_id=NEW.organization_id AND type='scheduled.timer')
         AND NOT EXISTS(SELECT 1 FROM outbox_events WHERE id=NEW.event_id
                  AND organization_id=NEW.organization_id
                  AND envelope->'payload'->>'timer_version_id'=NEW.rule_version_id::text)
      THEN RAISE EXCEPTION 'Timer run must bind its own exact version'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;
    """)
    for table, function in (
        ("task_deadline_events", "periodic_deadline_guard"),
        ("automation_timer_occurrences", "periodic_timer_guard"),
    ):
        op.execute(
            f"CREATE TRIGGER {table}_guard BEFORE INSERT ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION {function}()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_rewrite BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION automation_no_rewrite()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION automation_no_rewrite()"
        )
    op.execute(
        "CREATE TRIGGER automation_periodic_run_guard BEFORE INSERT ON automation_runs "
        "FOR EACH ROW EXECUTE FUNCTION periodic_run_guard()"
    )
