"""phase 6 automatic notification delivery evidence"""

import sqlalchemy as sa
from alembic import op

revision = "a5fa16a227ff"
down_revision = "73eddd554d17"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "number BETWEEN 1 AND 20 AND created BETWEEN 0 AND 1000 "
            "AND skipped BETWEEN 0 AND 1000 AND outcome IN ('completed','retry','dead_letter')",
            name=op.f("ck_notification_attempts_notification_attempt_contract"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "delivery_id"],
            ["outbox_deliveries.organization_id", "outbox_deliveries.id"],
            name=op.f("fk_notification_attempts_organization_id_outbox_deliveries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_attempts")),
        sa.UniqueConstraint(
            "organization_id", "delivery_id", "number", name="uq_notification_attempt"
        ),
    )
    op.add_column(
        "notifications",
        sa.Column("origin", sa.String(length=20), server_default="automation", nullable=False),
    )
    op.add_column("notifications", sa.Column("source_intent_id", sa.Uuid(), nullable=True))
    op.alter_column("notifications", "run_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("notifications", "position", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        "uq_notice_automatic_once",
        "notifications",
        ["organization_id", "event_id", "recipient_id"],
        unique=True,
        postgresql_where=sa.text("origin='automatic'"),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "notice_origin",
        "notifications",
        "(origin='automation' AND run_id IS NOT NULL AND position IS NOT NULL "
        "AND source_intent_id IS NULL) OR (origin='automatic' AND run_id IS NULL "
        "AND position IS NULL AND source_intent_id IS NOT NULL)",
    )
    install_guards()


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS(SELECT 1 FROM notification_attempts)
        OR EXISTS(SELECT 1 FROM notifications WHERE origin='automatic')
        OR EXISTS(SELECT 1 FROM outbox_events
                  WHERE type IN ('workflow.notification.requested','task.reminder.created'))
      THEN RAISE EXCEPTION 'Populated automatic notification downgrade refused; preserve evidence'
        USING ERRCODE='55000'; END IF;
    END $$;
    DROP TRIGGER notifications_automatic_guard ON notifications;
    DROP TRIGGER notifications_insert_guard ON notifications;
    CREATE TRIGGER notifications_insert_guard BEFORE INSERT ON notifications
      FOR EACH ROW EXECUTE FUNCTION notification_insert_guard();
    DROP FUNCTION automatic_notification_guard();
    """)
    op.drop_constraint(op.f("ck_notifications_notice_origin"), "notifications", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_notice_automatic_once",
        table_name="notifications",
        postgresql_where=sa.text("origin='automatic'"),
    )
    op.alter_column("notifications", "position", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("notifications", "run_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("notifications", "source_intent_id")
    op.drop_column("notifications", "origin")
    op.drop_table("notification_attempts")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION notification_attempt_guard()")


def install_guards() -> None:
    op.execute("""
    DROP TRIGGER notifications_insert_guard ON notifications;
    CREATE TRIGGER notifications_insert_guard BEFORE INSERT ON notifications
      FOR EACH ROW WHEN (NEW.origin='automation') EXECUTE FUNCTION notification_insert_guard();
    CREATE FUNCTION automatic_notification_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM outbox_events e JOIN outbox_deliveries d
          ON d.organization_id=e.organization_id AND d.event_id=e.id
        WHERE e.organization_id=NEW.organization_id AND e.id=NEW.event_id
          AND d.consumer='notifications' AND d.state IN ('pending','retry','dispatched')
          AND e.workspace_id=NEW.workspace_id
          AND e.project_id IS NOT DISTINCT FROM NEW.project_id
          AND e.envelope->'payload'->'recipient_ids' @> to_jsonb(NEW.recipient_id::text)
          AND NEW.created_at >= e.occurred_at
          AND (
            (NEW.source_kind='task' AND NEW.source_intent_id=e.id
              AND e.type IN ('task.created','task.due','task.overdue','task.reminder.created')
              AND NEW.topic=CASE WHEN e.type='task.created'
                THEN 'work_assigned' ELSE 'rule_notice' END
              AND e.envelope->'payload'->>'task_id'=NEW.source_id::text
              AND EXISTS(SELECT 1 FROM task_occurrences t
                WHERE t.organization_id=e.organization_id AND t.workspace_id=e.workspace_id
                  AND t.project_id IS NOT DISTINCT FROM e.project_id AND t.id=NEW.source_id
                  AND t.recipient_ids=e.envelope->'payload'->'recipient_ids')
              AND (e.type<>'task.reminder.created' OR EXISTS(SELECT 1 FROM task_reminders m
                WHERE m.id=e.id AND m.organization_id=e.organization_id AND m.task_id=NEW.source_id
                  AND e.envelope->'payload'->>'reminder_id'=m.id::text)))
            OR (NEW.source_kind='workflow'
              AND e.envelope->'payload'->>'workflow_instance_id'=NEW.source_id::text
              AND e.envelope->>'aggregate_id'=NEW.source_intent_id::text
              AND EXISTS(SELECT 1 FROM workflow_instances i JOIN workflows w
                ON w.organization_id=i.organization_id AND w.id=i.workflow_id
                WHERE i.id=NEW.source_id AND i.organization_id=e.organization_id
                  AND i.workspace_id=e.workspace_id
                  AND w.project_id IS NOT DISTINCT FROM e.project_id)
              AND ((e.type='workflow.step.entered' AND NEW.topic='review_requested'
                AND EXISTS(SELECT 1 FROM workflow_recipients r
                  WHERE r.organization_id=e.organization_id AND r.workspace_id=e.workspace_id
                    AND r.instance_id=NEW.source_id
                    AND r.step_id=NEW.source_intent_id AND r.user_id=NEW.recipient_id))
                OR (e.type='workflow.notification.requested' AND NEW.topic='rule_notice'
                  AND EXISTS(SELECT 1 FROM workflow_notifications n
                    WHERE n.id=NEW.source_intent_id AND n.organization_id=e.organization_id
                      AND n.instance_id=NEW.source_id
                      AND n.recipient_ids=e.envelope->'payload'->'recipient_ids'))))
          )
          AND EXISTS(SELECT 1 FROM audit_events a WHERE a.organization_id=e.organization_id
            AND a.aggregate_id=NEW.id AND a.type='notification.created' AND a.actor_id IS NULL
            AND a.request_id=d.id AND a.payload->>'target_id'=NEW.recipient_id::text
            AND a.payload->>'reason'='automatic_source_notice')
      ) THEN RAISE EXCEPTION 'Invalid automatic notification evidence'
        USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER notifications_automatic_guard BEFORE INSERT ON notifications
      FOR EACH ROW WHEN (NEW.origin='automatic') EXECUTE FUNCTION automatic_notification_guard();
    CREATE FUNCTION notification_attempt_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS(SELECT 1 FROM outbox_deliveries d
        WHERE d.organization_id=NEW.organization_id AND d.id=NEW.delivery_id
          AND d.consumer='notifications' AND d.attempts=NEW.number AND d.state=NEW.outcome
          AND d.error_code IS NOT DISTINCT FROM NEW.error_code
          AND EXISTS(SELECT 1 FROM audit_events a WHERE a.organization_id=d.organization_id
            AND a.aggregate_id=d.id AND a.type='outbox.notification.' || NEW.outcome
            AND a.request_id=d.id AND a.actor_id IS NULL))
      THEN RAISE EXCEPTION 'Invalid notification attempt evidence' USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER notification_attempt_insert_guard BEFORE INSERT ON notification_attempts
      FOR EACH ROW EXECUTE FUNCTION notification_attempt_guard();
    CREATE TRIGGER notification_attempts_immutable BEFORE UPDATE OR DELETE ON notification_attempts
      FOR EACH ROW EXECUTE FUNCTION automation_no_rewrite();
    CREATE TRIGGER notification_attempts_no_truncate BEFORE TRUNCATE ON notification_attempts
      FOR EACH STATEMENT EXECUTE FUNCTION automation_no_rewrite();
    """)
