"""phase 4 schedules shared tasks shifts and reminders"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "b71acf0449b2"
down_revision = "dbd58764eb86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_milestones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_project_milestones_organization_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_milestones")),
    )
    op.create_table(
        "schedule_shifts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_schedule_shifts_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_schedule_shifts_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_shifts")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "code", "number", name="uq_shift_code_number"
        ),
    )
    op.create_index(
        "ix_shifts_scope_cursor",
        "schedule_shifts",
        ["organization_id", "workspace_id", "project_id", "id"],
        unique=False,
    )
    op.create_table(
        "schedule_triggers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_schedule_triggers_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_schedule_triggers_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_triggers")),
    )
    op.create_index(
        "ix_schedule_triggers_scope_time",
        "schedule_triggers",
        ["organization_id", "workspace_id", "project_id", "code", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active_number", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "revision > 0 AND (active_number IS NULL OR active_number > 0)",
            name=op.f("ck_schedules_schedule_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_schedules_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_schedules_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("organization_id", "workspace_id", "id", name="uq_schedules_scope"),
    )
    op.create_index(
        "ix_schedules_scope_cursor",
        "schedules",
        ["organization_id", "workspace_id", "project_id", "id"],
        unique=False,
    )
    op.create_table(
        "schedule_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("form_version_id", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "(state='draft' AND activated_at IS NULL AND content_sha256 IS NULL "
            "AND form_version_id IS NULL) OR (state<>'draft' AND activated_at IS NOT NULL "
            "AND content_sha256 IS NOT NULL AND form_version_id IS NOT NULL)",
            name=op.f("ck_schedule_versions_schedule_activation"),
        ),
        sa.CheckConstraint(
            "number > 0 AND revision > 0 AND state IN ('draft','active','paused','retired')",
            name=op.f("ck_schedule_versions_schedule_version_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "form_version_id"],
            ["form_versions.organization_id", "form_versions.workspace_id", "form_versions.id"],
            name=op.f("fk_schedule_versions_organization_id_form_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "schedule_id"],
            ["schedules.organization_id", "schedules.workspace_id", "schedules.id"],
            name=op.f("fk_schedule_versions_organization_id_schedules"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_versions")),
        sa.UniqueConstraint(
            "organization_id", "schedule_id", "number", name="uq_schedule_version_number"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "schedule_id",
            "id",
            "number",
            name="uq_schedule_version_exact",
        ),
    )
    op.create_index(
        "ix_schedule_versions_cursor",
        "schedule_versions",
        ["organization_id", "schedule_id", "id"],
        unique=False,
    )
    op.create_table(
        "task_occurrences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_version_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_number", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("form_version_id", sa.Uuid(), nullable=False),
        sa.Column("form_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("occurs_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assignment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assignment_key", sa.String(length=100), nullable=False),
        sa.Column("recipient_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reminder_offsets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("claimant_id", sa.Uuid(), nullable=True),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(state IN ('open','superseded') AND claimant_id IS NULL AND submission_id IS NULL) "
            "OR state='cancelled' OR (state IN ('in_progress','submitted','awaiting_review',"
            "'returned','approved') AND claimant_id IS NOT NULL AND submission_id IS NOT NULL)",
            name=op.f("ck_task_occurrences_task_claim"),
        ),
        sa.CheckConstraint(
            "revision > 0 AND due_at >= occurs_at AND state IN ('open','in_progress',"
            "'submitted','awaiting_review','returned','approved','cancelled','superseded')",
            name=op.f("ck_task_occurrences_task_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "claimant_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_task_occurrences_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "form_id", "form_version_id", "form_number"],
            [
                "form_versions.organization_id",
                "form_versions.workspace_id",
                "form_versions.form_id",
                "form_versions.id",
                "form_versions.number",
            ],
            name=op.f("fk_task_occurrences_organization_id_form_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_task_occurrences_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "schedule_id",
                "schedule_version_id",
                "schedule_number",
            ],
            [
                "schedule_versions.organization_id",
                "schedule_versions.workspace_id",
                "schedule_versions.schedule_id",
                "schedule_versions.id",
                "schedule_versions.number",
            ],
            name=op.f("fk_task_occurrences_organization_id_schedule_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "submission_id", "claimant_id"],
            [
                "submissions.organization_id",
                "submissions.workspace_id",
                "submissions.id",
                "submissions.owner_id",
            ],
            name=op.f("fk_task_occurrences_organization_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_occurrences")),
        sa.UniqueConstraint(
            "organization_id",
            "schedule_version_id",
            "occurs_at",
            "assignment_key",
            name="uq_task_materialization",
        ),
        sa.UniqueConstraint("organization_id", "submission_id", name="uq_task_submission"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id", name="uq_task_scope"),
    )
    op.create_index(
        "ix_tasks_scope_state_due_cursor",
        "task_occurrences",
        ["organization_id", "workspace_id", "project_id", "state", "due_at", "id"],
        unique=False,
    )
    op.create_table(
        "task_recipients",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["users.organization_id", "users.id"],
            name=op.f("fk_task_recipients_organization_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "task_id"],
            [
                "task_occurrences.organization_id",
                "task_occurrences.workspace_id",
                "task_occurrences.id",
            ],
            name=op.f("fk_task_recipients_organization_id_task_occurrences"),
        ),
        sa.PrimaryKeyConstraint("task_id", "user_id", name=op.f("pk_task_recipients")),
    )
    op.create_index(
        "ix_task_recipients_personal",
        "task_recipients",
        ["organization_id", "workspace_id", "user_id", "task_id"],
        unique=False,
    )
    op.create_table(
        "task_reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("offset_seconds", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "task_id"],
            [
                "task_occurrences.organization_id",
                "task_occurrences.workspace_id",
                "task_occurrences.id",
            ],
            name=op.f("fk_task_reminders_organization_id_task_occurrences"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_reminders")),
        sa.UniqueConstraint(
            "organization_id", "task_id", "offset_seconds", name="uq_task_reminder_once"
        ),
    )
    op.create_index(
        "ix_task_reminders_scope_cursor",
        "task_reminders",
        ["organization_id", "workspace_id", "task_id", "id"],
        unique=False,
    )
    op.execute("""
    CREATE FUNCTION protect_phase4_record() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP IN ('DELETE','TRUNCATE') THEN
        RAISE EXCEPTION 'Phase 4 history is retained' USING ERRCODE='55000';
      END IF;
      IF TG_OP='INSERT' AND TG_TABLE_NAME='task_occurrences' THEN
        IF NOT EXISTS (
          SELECT 1 FROM schedules s JOIN schedule_versions v
          ON v.schedule_id=s.id AND v.organization_id=s.organization_id
          WHERE s.organization_id=NEW.organization_id AND s.workspace_id=NEW.workspace_id
          AND s.id=NEW.schedule_id AND v.id=NEW.schedule_version_id
          AND s.project_id IS NOT DISTINCT FROM NEW.project_id
          AND v.form_version_id=NEW.form_version_id
          AND v.definition->>'form_id'=NEW.form_id::text
          AND (v.definition->>'form_number')::integer=NEW.form_number
        ) THEN RAISE EXCEPTION 'Task exact scope/version mismatch' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END IF;
      IF TG_TABLE_NAME IN ('schedule_shifts','schedule_triggers','project_milestones',
        'task_recipients','task_reminders') THEN
        RAISE EXCEPTION 'Immutable Phase 4 snapshot' USING ERRCODE='55000';
      END IF;
      IF NEW.revision<>OLD.revision+1 THEN
        RAISE EXCEPTION 'Revision must increment' USING ERRCODE='55000';
      END IF;
      IF TG_TABLE_NAME='schedules' THEN
        IF (to_jsonb(NEW)-'revision'-'active_number') IS DISTINCT FROM
           (to_jsonb(OLD)-'revision'-'active_number') THEN
          RAISE EXCEPTION 'Immutable schedule identity' USING ERRCODE='55000';
        END IF;
      ELSIF TG_TABLE_NAME='schedule_versions' THEN
        IF (to_jsonb(NEW)-'revision'-'definition'-'state'-'form_version_id'
            -'activated_at'-'content_sha256')
          IS DISTINCT FROM
          (to_jsonb(OLD)-'revision'-'definition'-'state'-'form_version_id'
           -'activated_at'-'content_sha256')
          THEN RAISE EXCEPTION 'Immutable version identity' USING ERRCODE='55000'; END IF;
        IF OLD.state='draft' THEN
          IF NEW.state NOT IN ('draft','active') THEN
            RAISE EXCEPTION 'Invalid activation' USING ERRCODE='55000'; END IF;
        ELSE
          IF (to_jsonb(NEW)-'revision'-'state') IS DISTINCT FROM (to_jsonb(OLD)-'revision'-'state')
          OR NOT ((OLD.state='active' AND NEW.state IN ('paused','retired'))
             OR (OLD.state='paused' AND NEW.state IN ('active','retired')))
          THEN RAISE EXCEPTION 'Immutable active schedule' USING ERRCODE='55000'; END IF;
        END IF;
      ELSIF TG_TABLE_NAME='task_occurrences' THEN
        IF (to_jsonb(NEW)-'revision'-'state'-'claimant_id'-'submission_id') IS DISTINCT FROM
          (to_jsonb(OLD)-'revision'-'state'-'claimant_id'-'submission_id')
        OR NOT ((OLD.state='open' AND NEW.state IN ('in_progress','cancelled','superseded'))
             OR (OLD.state='in_progress' AND NEW.state IN ('submitted','cancelled')))
        OR (OLD.claimant_id IS NOT NULL AND
           (NEW.claimant_id IS DISTINCT FROM OLD.claimant_id
            OR NEW.submission_id IS DISTINCT FROM OLD.submission_id))
        THEN RAISE EXCEPTION 'Immutable task history/claim' USING ERRCODE='55000'; END IF;
        IF NEW.claimant_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM task_recipients
          WHERE task_id=NEW.id AND organization_id=NEW.organization_id AND user_id=NEW.claimant_id)
          THEN RAISE EXCEPTION 'Claimant not assigned' USING ERRCODE='23514'; END IF;
        IF NEW.state='submitted' AND NOT EXISTS (SELECT 1 FROM submissions
          WHERE organization_id=NEW.organization_id AND id=NEW.submission_id
          AND state='submitted' AND form_version_id=NEW.form_version_id)
          THEN RAISE EXCEPTION 'Task requires exact submitted snapshot'
          USING ERRCODE='23514'; END IF;
      END IF;
      RETURN NEW;
    END $$;
    """)
    for table in (
        "schedules",
        "schedule_versions",
        "schedule_shifts",
        "schedule_triggers",
        "project_milestones",
        "task_occurrences",
        "task_recipients",
        "task_reminders",
    ):
        op.execute(
            f"CREATE TRIGGER protect_{table}_changes BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_phase4_record()"
        )
        op.execute(
            f"CREATE TRIGGER protect_{table}_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION protect_phase4_record()"
        )
    op.execute(
        "CREATE TRIGGER protect_task_exact_insert BEFORE INSERT ON task_occurrences "
        "FOR EACH ROW EXECUTE FUNCTION protect_phase4_record()"
    )


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM schedules) OR EXISTS (SELECT 1 FROM schedule_versions)
      OR EXISTS (SELECT 1 FROM schedule_shifts) OR EXISTS (SELECT 1 FROM schedule_triggers)
      OR EXISTS (SELECT 1 FROM project_milestones) OR EXISTS (SELECT 1 FROM task_occurrences)
      OR EXISTS (SELECT 1 FROM task_recipients) OR EXISTS (SELECT 1 FROM task_reminders)
      THEN RAISE EXCEPTION 'Populated Phase 4 rollback requires backup/restore and reconciliation';
      END IF;
    END $$;
    """)
    op.execute("DROP FUNCTION protect_phase4_record() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_reminders_scope_cursor", table_name="task_reminders")
    op.drop_table("task_reminders")
    op.drop_index("ix_task_recipients_personal", table_name="task_recipients")
    op.drop_table("task_recipients")
    op.drop_index("ix_tasks_scope_state_due_cursor", table_name="task_occurrences")
    op.drop_table("task_occurrences")
    op.drop_index("ix_schedule_versions_cursor", table_name="schedule_versions")
    op.drop_table("schedule_versions")
    op.drop_index("ix_schedules_scope_cursor", table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_schedule_triggers_scope_time", table_name="schedule_triggers")
    op.drop_table("schedule_triggers")
    op.drop_index("ix_shifts_scope_cursor", table_name="schedule_shifts")
    op.drop_table("schedule_shifts")
    op.drop_table("project_milestones")
    # ### end Alembic commands ###
