"""phase 5 immutable workflow definitions"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "e049d194ba38"
down_revision = "b71acf0449b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active_number", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "revision > 0 AND (active_number IS NULL OR active_number > 0)",
            name=op.f("ck_workflows_workflow_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name=op.f("fk_workflows_organization_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_workflows_organization_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
        sa.UniqueConstraint("organization_id", "workspace_id", "id", name="uq_workflows_scope"),
    )
    op.create_index(
        "ix_workflows_scope_cursor",
        "workflows",
        ["organization_id", "workspace_id", "project_id", "id"],
        unique=False,
    )
    op.create_table(
        "workflow_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("form_version_id", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "(state='draft' AND activated_at IS NULL AND content_sha256 IS NULL "
            "AND form_version_id IS NULL) OR (state<>'draft' AND activated_at IS NOT NULL "
            "AND content_sha256 IS NOT NULL AND form_version_id IS NOT NULL)",
            name=op.f("ck_workflow_versions_workflow_activation"),
        ),
        sa.CheckConstraint(
            "number > 0 AND revision > 0 AND state IN ('draft','active','retired')",
            name=op.f("ck_workflow_versions_workflow_version_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "form_version_id"],
            ["form_versions.organization_id", "form_versions.workspace_id", "form_versions.id"],
            name=op.f("fk_workflow_versions_organization_id_form_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "workflow_id"],
            ["workflows.organization_id", "workflows.workspace_id", "workflows.id"],
            name=op.f("fk_workflow_versions_organization_id_workflows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint(
            "organization_id", "workflow_id", "number", name="uq_workflow_version_number"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "workflow_id",
            "id",
            "number",
            name="uq_workflow_version_exact",
        ),
    )
    op.create_index(
        "ix_workflow_versions_cursor",
        "workflow_versions",
        ["organization_id", "workspace_id", "workflow_id", "id"],
        unique=False,
    )
    op.execute("""
    CREATE FUNCTION protect_workflow_definition() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP IN ('DELETE', 'TRUNCATE') THEN
        RAISE EXCEPTION 'Workflow history cannot be deleted' USING ERRCODE='55000';
      END IF;
      IF TG_OP='UPDATE' THEN
        IF NEW.revision <> OLD.revision + 1 THEN
          RAISE EXCEPTION 'Workflow revision must advance once' USING ERRCODE='55000';
        END IF;
        IF TG_TABLE_NAME='workflows' THEN
          IF (to_jsonb(NEW)-ARRAY['revision','active_number']) IS DISTINCT FROM
             (to_jsonb(OLD)-ARRAY['revision','active_number']) THEN
            RAISE EXCEPTION 'Workflow identity is immutable' USING ERRCODE='55000';
          END IF;
        ELSE
          IF (NEW.id,NEW.organization_id,NEW.workspace_id,NEW.workflow_id,NEW.number)
             IS DISTINCT FROM
             (OLD.id,OLD.organization_id,OLD.workspace_id,OLD.workflow_id,OLD.number) THEN
            RAISE EXCEPTION 'Workflow version identity is immutable' USING ERRCODE='55000';
          END IF;
          IF OLD.state <> 'draft' AND (
            NOT (OLD.state='active' AND NEW.state='retired') OR
            (to_jsonb(NEW)-ARRAY['revision','state']) IS DISTINCT FROM
            (to_jsonb(OLD)-ARRAY['revision','state'])
          ) THEN
            RAISE EXCEPTION 'Activated workflow version is immutable' USING ERRCODE='55000';
          END IF;
          IF OLD.state='draft' AND NEW.state NOT IN ('draft','active') THEN
            RAISE EXCEPTION 'Invalid workflow activation' USING ERRCODE='55000';
          END IF;
        END IF;
      END IF;
      IF TG_TABLE_NAME='workflow_versions' THEN
       IF NEW.state <> 'draft' THEN
        IF NOT EXISTS (
          SELECT 1 FROM form_versions fv
          JOIN forms f ON f.id=fv.form_id AND f.organization_id=fv.organization_id
          JOIN workflows w ON w.id=NEW.workflow_id AND w.organization_id=NEW.organization_id
          WHERE fv.id=NEW.form_version_id AND fv.organization_id=NEW.organization_id
          AND fv.workspace_id=NEW.workspace_id
          AND f.workspace_id=NEW.workspace_id
          AND f.project_id IS NOT DISTINCT FROM w.project_id
          AND fv.form_id=(NEW.definition->>'form_id')::uuid
          AND fv.number=(NEW.definition->>'form_number')::integer
        ) THEN
          RAISE EXCEPTION 'Workflow form scope or version mismatch' USING ERRCODE='55000';
        END IF;
       END IF;
      END IF;
      IF TG_TABLE_NAME='workflows' THEN
       IF NEW.active_number IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM workflow_versions v
          WHERE v.organization_id=NEW.organization_id AND v.workspace_id=NEW.workspace_id
          AND v.workflow_id=NEW.id AND v.number=NEW.active_number AND v.state='active') THEN
          RAISE EXCEPTION 'Workflow active version required' USING ERRCODE='55000';
        END IF;
       END IF;
      END IF;
      RETURN NEW;
    END $$;
    """)
    for table in ("workflows", "workflow_versions"):
        op.execute(
            f"CREATE TRIGGER protect_{table} BEFORE INSERT OR UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_workflow_definition()"
        )
        op.execute(
            f"CREATE TRIGGER protect_{table}_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION protect_workflow_definition()"
        )


def downgrade() -> None:
    op.execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM workflows) OR EXISTS (SELECT 1 FROM workflow_versions) THEN
        RAISE EXCEPTION 'Populated workflow downgrade refused; restore and reconcile backup'
          USING ERRCODE='55000';
      END IF;
    END $$;
    DROP FUNCTION protect_workflow_definition() CASCADE;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_versions_cursor", table_name="workflow_versions")
    op.drop_table("workflow_versions")
    op.drop_index("ix_workflows_scope_cursor", table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
